# Generated by Django 3.1.4 on 2021-03-07 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prof.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(default='avatars/avatar.svg', upload_to=prof.models.path_upload_avatars)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('about', models.CharField(blank=True, max_length=400, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
