# Generated by Django 3.1.4 on 2020-12-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20201227_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
