# Generated by Django 3.1.4 on 2020-12-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20201227_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
