# Generated by Django 3.1.4 on 2020-12-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post_for_comment',
        ),
    ]
