# Generated by Django 3.1.4 on 2020-12-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20201230_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_for_comment',
            new_name='post',
        ),
    ]
