# Generated by Django 3.1.4 on 2021-01-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_auto_20210101_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=400, verbose_name='your comment'),
        ),
    ]
