# Generated by Django 3.1.4 on 2021-01-03 00:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_auto_20210102_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='avalaible',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
