# Generated by Django 3.1.4 on 2021-02-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_auto_20210103_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
