# Generated by Django 3.1.4 on 2021-03-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
        ('first', '0020_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Cars', 'Cars'), ('It', 'It'), ('Sport', 'Sport')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.profile', verbose_name='author_comm'),
        ),
        migrations.DeleteModel(
            name='CategoryArt',
        ),
    ]
