# Generated by Django 3.1.4 on 2021-03-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
        ('first', '0021_auto_20210307_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_likes',
            field=models.ManyToManyField(to='prof.Profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='prof.profile'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
