# Generated by Django 3.1.4 on 2021-03-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0022_auto_20210308_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post_likes',
            new_name='likes',
        ),
    ]
